// Code generated by counterfeiter. DO NOT EDIT.
package llmfakes

import (
	"sync"

	"github.com/jlcheng/jcllm/llm"
)

type FakeRoleMapper struct {
	ToGenericRoleStub        func(string) string
	toGenericRoleMutex       sync.RWMutex
	toGenericRoleArgsForCall []struct {
		arg1 string
	}
	toGenericRoleReturns struct {
		result1 string
	}
	toGenericRoleReturnsOnCall map[int]struct {
		result1 string
	}
	ToProviderRoleStub        func(string) string
	toProviderRoleMutex       sync.RWMutex
	toProviderRoleArgsForCall []struct {
		arg1 string
	}
	toProviderRoleReturns struct {
		result1 string
	}
	toProviderRoleReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRoleMapper) ToGenericRole(arg1 string) string {
	fake.toGenericRoleMutex.Lock()
	ret, specificReturn := fake.toGenericRoleReturnsOnCall[len(fake.toGenericRoleArgsForCall)]
	fake.toGenericRoleArgsForCall = append(fake.toGenericRoleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ToGenericRoleStub
	fakeReturns := fake.toGenericRoleReturns
	fake.recordInvocation("ToGenericRole", []interface{}{arg1})
	fake.toGenericRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRoleMapper) ToGenericRoleCallCount() int {
	fake.toGenericRoleMutex.RLock()
	defer fake.toGenericRoleMutex.RUnlock()
	return len(fake.toGenericRoleArgsForCall)
}

func (fake *FakeRoleMapper) ToGenericRoleCalls(stub func(string) string) {
	fake.toGenericRoleMutex.Lock()
	defer fake.toGenericRoleMutex.Unlock()
	fake.ToGenericRoleStub = stub
}

func (fake *FakeRoleMapper) ToGenericRoleArgsForCall(i int) string {
	fake.toGenericRoleMutex.RLock()
	defer fake.toGenericRoleMutex.RUnlock()
	argsForCall := fake.toGenericRoleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRoleMapper) ToGenericRoleReturns(result1 string) {
	fake.toGenericRoleMutex.Lock()
	defer fake.toGenericRoleMutex.Unlock()
	fake.ToGenericRoleStub = nil
	fake.toGenericRoleReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeRoleMapper) ToGenericRoleReturnsOnCall(i int, result1 string) {
	fake.toGenericRoleMutex.Lock()
	defer fake.toGenericRoleMutex.Unlock()
	fake.ToGenericRoleStub = nil
	if fake.toGenericRoleReturnsOnCall == nil {
		fake.toGenericRoleReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.toGenericRoleReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeRoleMapper) ToProviderRole(arg1 string) string {
	fake.toProviderRoleMutex.Lock()
	ret, specificReturn := fake.toProviderRoleReturnsOnCall[len(fake.toProviderRoleArgsForCall)]
	fake.toProviderRoleArgsForCall = append(fake.toProviderRoleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ToProviderRoleStub
	fakeReturns := fake.toProviderRoleReturns
	fake.recordInvocation("ToProviderRole", []interface{}{arg1})
	fake.toProviderRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRoleMapper) ToProviderRoleCallCount() int {
	fake.toProviderRoleMutex.RLock()
	defer fake.toProviderRoleMutex.RUnlock()
	return len(fake.toProviderRoleArgsForCall)
}

func (fake *FakeRoleMapper) ToProviderRoleCalls(stub func(string) string) {
	fake.toProviderRoleMutex.Lock()
	defer fake.toProviderRoleMutex.Unlock()
	fake.ToProviderRoleStub = stub
}

func (fake *FakeRoleMapper) ToProviderRoleArgsForCall(i int) string {
	fake.toProviderRoleMutex.RLock()
	defer fake.toProviderRoleMutex.RUnlock()
	argsForCall := fake.toProviderRoleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRoleMapper) ToProviderRoleReturns(result1 string) {
	fake.toProviderRoleMutex.Lock()
	defer fake.toProviderRoleMutex.Unlock()
	fake.ToProviderRoleStub = nil
	fake.toProviderRoleReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeRoleMapper) ToProviderRoleReturnsOnCall(i int, result1 string) {
	fake.toProviderRoleMutex.Lock()
	defer fake.toProviderRoleMutex.Unlock()
	fake.ToProviderRoleStub = nil
	if fake.toProviderRoleReturnsOnCall == nil {
		fake.toProviderRoleReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.toProviderRoleReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeRoleMapper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.toGenericRoleMutex.RLock()
	defer fake.toGenericRoleMutex.RUnlock()
	fake.toProviderRoleMutex.RLock()
	defer fake.toProviderRoleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRoleMapper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ llm.RoleMapper = new(FakeRoleMapper)
