name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'  # or your preferred version

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest  # or pin to a specific version

      - name: Run GoReleaser
        run: goreleaser release --rm-dist
